# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
#- main
- master

pool:
  #name: 'azure pipelines'
  #vmImage: 'windows-latest'
  name: 'default'

variables:
  solution: 'P2_2ManyCooks.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core SDK'
  inputs:
    packageType: 'sdk'
    version: '5.0.x'
    # performMultiLevelLookup: true
    # includePreviewVersions: false # Required 'true' to use preview versions

- task: UseDotNet@2
  displayName: 'Install .NET Core Runtime'
  inputs:
    packageType: 'runtime'
    version: '2.x'
    # performMultiLevelLookup: true

- task: JavaToolInstaller@0
  inputs:
    versionSpec: '11'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'LocalDirectory'
    jdkFile: 'D:/jdk-11.0.10_windows-x64_bin.zip'
    jdkDestinationDirectory: '/builds/binaries/externals'
    cleanDestinationDirectory: true

- task: NodeTool@0
  inputs:
    versionSpec: '11.x'

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud'
    organization: '2manycooksinthekitchen'
    scannerMode: 'MSBuild'
    projectKey: '2ManyCooksInTheKitchen_InTheKitchenApp'
    projectName: 'InTheKitchenApp'
    # extraProperties: |
    #   sonar.exclusions=**/AngularTest/*
    #   sonar.cs.opencover.reportsPaths=$(Agent.TempDirectory)/*/coverage.opencover.xml
#this will restore and build the directory.
- task: DotNetCoreCLI@2
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True

# this code takes all the files in $(Build.ArtifactStagingDirectory) and uploads them as an artifact of your build.
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'EventFunctionsP2'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'Testing/*.csproj'
    arguments: '--configuration $(buildConfiguration) --collect "xplat code coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura,opencover'
    testRunTitle: 'Dotnet tests running'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '**/coburtura/coverage.xml'

- task: SonarCloudAnalyze@1

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'


- task: DotNetCoreCLI@2
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True

# - task: DotNetCoreCLI@2
#   displayName: 'Publishing'
#   inputs:
#     command: 'publish'
#     publishWebProjects: true
#     modifyOutputPath: false
#     workingDirectory: 'WebApi'
#     projects: '$(solution)'
#     zipAfterPublish: true

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1(9397ed34-7cce-4ecb-964e-961c2674cac7)'
    appType: 'webApp'
    WebAppName: 'inthekitchen'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'

