# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main
- master

pool:
  name: 'default'

variables:
  buildConfiguration: 'Release'



steps:


# SonarCloud Prepare Analysis Configuration - Must be before build step
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloudServiceConnection'
    organization: '2manycooks'
    scannerMode: 'MSBuild'
    projectKey: '2ManyCooks_P2_2ManyCooks.git'
    projectName: 'P2_2ManyCooks.git'


- script: dotnet --info #dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

## Uncomment -Run Code Analysis and -Publish Quality Gate Result once there is code to be analyzed
# SonarCloud Run Code Analysis
#- task: SonarCloudAnalyze@1
  
# SonarCloud Publish Quality Gate Result
#- task: SonarCloudPublish@1
#  inputs:
#    pollingTimeoutSec: '300'

